"""your_migration_description

Revision ID: 7d4d45691e05
Revises: 7113d03b2a94
Create Date: 2025-06-23 05:19:15.805314

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7d4d45691e05'
down_revision: Union[str, Sequence[str], None] = '7113d03b2a94'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('content', sa.Column('category', sa.String(length=10), nullable=True))
    op.add_column('content', sa.Column('subject', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('content', 'subject')
    op.drop_column('content', 'category')
    # ### end Alembic commands ###
