"""Remove deleted model tables

Revision ID: ec24e1660c33
Revises: 93a11a844473
Create Date: 2025-06-23 11:47:36.915135

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ec24e1660c33'
down_revision: Union[str, Sequence[str], None] = '93a11a844473'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('classifications')
    op.drop_table('senders')
    op.drop_table('source_metadata')
    op.drop_table('content_senders')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('content_senders',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('content_id', sa.VARCHAR(length=36), nullable=False),
    sa.Column('sender_id', sa.INTEGER(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['content_id'], ['content.id'], ),
    sa.ForeignKeyConstraint(['sender_id'], ['senders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('source_metadata',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('content_id', sa.VARCHAR(length=36), nullable=False),
    sa.Column('metadata_source', sa.VARCHAR(length=50), nullable=False),
    sa.Column('metadata_id', sa.VARCHAR(length=255), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['content_id'], ['content.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('senders',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), nullable=False),
    sa.Column('email', sa.VARCHAR(length=255), nullable=True),
    sa.Column('phone', sa.VARCHAR(length=50), nullable=True),
    sa.Column('platform', sa.VARCHAR(length=50), nullable=False),
    sa.Column('platform_user_id', sa.VARCHAR(length=255), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('classifications',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('content_id', sa.VARCHAR(length=36), nullable=False),
    sa.Column('category', sa.VARCHAR(length=50), nullable=False),
    sa.Column('confidence', sa.FLOAT(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['content_id'], ['content.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
